### ISSUE TITLE
Unable to run x-diff

### ISSUE THREAD

**Issue by satkatai** [albfan/x-diff#1]
Hi, I have installed as per the instructions  but output file is not generating after running. It is printing below lines in the terminal. It is only parsing first xml and exiting. I have tried on my xmls also using run.sh but facing same issue. I think while initialising the Parser , I am facing error. Please help me if possible.

```
user1982:x-diff-master skth$ ./test.sh 
Parsing input1
org.apache.xerces.parsers.SAXParser
user1982:x-diff-master skth$ 
```

**Comment by albfan** [comment]
I suppose you don't have served.jar avaliable.

See that output comes before do anything else

https://github.com/albfan/x-diff/blob/master/XDiff.java#L86

So run getdependencies.sh before run test.

Can you provide a PR fixing instructions on README?

In long term this needs to migrate to maven, gradle or meson to be build and run without manual steps

**Comment by satkatai** [comment]
Yeah, I did not run getdependencies.sh before running test.sh. Now it is working fine.Thanks.
